import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { ShieldCheck, ArrowLeft, Scale, FileText } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service & Conditions',
  description: 'Zelsis Terms of Service, code verification conditions, liability limitations, and subscription billing agreements.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0D0D0D] text-[#F8FAFC] p-6 sm:p-12 font-sans">
      <div className="max-w-3xl mx-auto flex flex-col gap-8">
        <div className="flex items-center justify-between">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-xs font-mono text-[#888888] hover:text-[#FFFFFF] transition-colors"
          >
            <ArrowLeft size={14} />
            <span>Back to Home</span>
          </Link>
          <div className="flex items-center gap-3">
            <Link
              href="/mesafeli-satis"
              className="text-xs font-mono text-emerald-400 hover:underline"
            >
              Mesafeli Satış Sözleşmesi (TR)
            </Link>
            <span className="text-[#333]">•</span>
            <Link
              href="/privacy"
              className="text-xs font-mono text-emerald-400 hover:underline"
            >
              Privacy Policy
            </Link>
          </div>
        </div>

        <div>
          <div className="flex items-center gap-2.5 mb-2">
            <ShieldCheck size={24} className="text-[#10B981]" />
            <h1 className="text-2xl sm:text-3xl font-extrabold text-[#FFFFFF] tracking-tight">
              Terms of Service &amp; User Agreement
            </h1>
          </div>
          <p className="text-xs font-mono text-[#888888]">
            Last Updated: September 10, 2026 // Version 2.0.0
          </p>
        </div>

        <div className="flex flex-col gap-6 text-xs sm:text-sm text-[#CCCCCC] leading-relaxed border-t border-[#262626] pt-6">
          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">1. Terms Agreement</h2>
            <p>
              By accessing, browsing, or utilizing the Zelsis Pre-Flight Release Gate SaaS platform (&quot;Service&quot;), you agree to be bound by these Terms of Service. If you are accepting on behalf of an organization or corporate entity, you represent and warrant that you possess full authority to bind that entity to these Terms.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">2. Scope of Service &amp; Advisor Disclaimer</h2>
            <p>
              Zelsis provides automated static analysis, security secret detection, design token hygiene checks, and pre-flight deployment gates. <strong>The audit scores, rule evaluations, and remediation prompts generated by Zelsis are advisory tools designed to assist engineering teams. They do not constitute formal legal counsel, regulatory audit certification, or infallible security guarantees.</strong> Users remain solely responsible for the architecture, security, and deployment readiness of their software.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">3. Subscriptions, Fees &amp; Digital Fulfillment</h2>
            <p>
              Access to premium rulesets, enterprise exports, and automated gates requires a paid subscription (Pro or Enterprise). Fees are billed in advance on a recurring monthly or annual basis. Turkish customers are subject to statutory 20% KDV.
            </p>
            <p className="text-[#AAAAAA] text-xs">
              Pursuant to consumer protection regulations for digital SaaS goods delivered instantaneously upon payment, digital subscriptions cannot be returned once provisioned, except where mandated by applicable consumer law. For details, see our{' '}
              <Link href="/mesafeli-satis" className="text-emerald-400 underline">
                Mesafeli Satış Sözleşmesi
              </Link>.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">4. Acceptable Use &amp; Code Ownership</h2>
            <p>
              You represent that you own or possess valid licensing rights for all repositories submitted to the scanner. You agree not to: (a) scan repositories without proper authorization; (b) reverse-engineer or attempt to extract source algorithms of the Zelsis scanner engine; or (c) probe, scan, or breach system boundaries or rate limit controls.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">5. Limitation of Liability &amp; Warranty Disclaimer</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ZELSIS IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. IN NO EVENT SHALL ZELSIS, ITS OFFICERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA CORRUPTION, DEPLOYMENT DOWNTIME, OR REGULATORY FINES ARISING FROM THE USE OF THE SERVICE.
            </p>
            <p>
              OUR TOTAL AGGREGATE LIABILITY UNDER THESE TERMS SHALL NOT EXCEED THE TOTAL AMOUNT ACTUALLY PAID BY YOU TO ZELSIS IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">6. Termination &amp; Account Erasure</h2>
            <p>
              You may terminate your account at any time via the Project Settings dashboard. We reserve the right to suspend or terminate accounts that violate acceptable use or attempt malicious exploitation of platform infrastructure.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">7. Governing Law &amp; Dispute Resolution</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the Republic of Turkey, without giving effect to any principles of conflicts of law. Any dispute arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the Istanbul (Çağlayan) Courts and Execution Offices.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">8. Contact &amp; Notices</h2>
            <p className="font-mono text-xs text-emerald-400">
              Legal Desk: legal@zelsis.com // General: contact@zelsis.com
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
