import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { ShieldCheck, ArrowLeft } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service & Conditions',
  description: 'Zelsis Terms of Service, code verification conditions, liability limitations, and global subscription billing agreements.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0D0D0D] text-[#F8FAFC] p-6 sm:p-12 font-sans">
      <div className="max-w-3xl mx-auto flex flex-col gap-8">
        <div className="flex items-center justify-between">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-xs font-mono text-[#888888] hover:text-[#FFFFFF] transition-colors"
          >
            <ArrowLeft size={14} />
            <span>Back to Home</span>
          </Link>
          <div className="flex items-center gap-3">
            <Link
              href="/cookies"
              className="text-xs font-mono text-emerald-400 hover:underline"
            >
              Cookie Policy
            </Link>
            <span className="text-[#333]">/</span>
            <Link
              href="/privacy"
              className="text-xs font-mono text-emerald-400 hover:underline"
            >
              Privacy Policy
            </Link>
          </div>
        </div>

        <div>
          <div className="flex items-center gap-2.5 mb-2">
            <ShieldCheck size={24} className="text-[#10B981]" />
            <h1 className="text-2xl sm:text-3xl font-extrabold text-[#FFFFFF] tracking-tight">
              Terms of Service &amp; User Agreement
            </h1>
          </div>
          <p className="text-xs font-mono text-[#888888]">
            Last Updated: September 10, 2026 // Global SaaS Edition (Version 2.1.0)
          </p>
        </div>

        <div className="flex flex-col gap-6 text-xs sm:text-sm text-[#CCCCCC] leading-relaxed border-t border-[#262626] pt-6">
          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">1. Terms Agreement</h2>
            <p>
              By accessing, browsing, or utilizing the Zelsis Pre-Flight Release Gate SaaS platform (&quot;Service&quot;), you agree to be bound by these Terms of Service. If you are accepting on behalf of an organization or corporate entity, you represent and warrant that you possess full authority to bind that entity to these Terms.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">2. Scope of Service &amp; Advisor Disclaimer</h2>
            <p>
              Zelsis provides automated static analysis, security secret detection, design token hygiene checks, and pre-flight deployment gates. <strong>The audit scores, rule evaluations, and remediation prompts generated by Zelsis are advisory tools designed to assist engineering teams. They do not constitute formal legal counsel, regulatory audit certification, or infallible security guarantees.</strong> Users remain solely responsible for the architecture, security, and deployment readiness of their software.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">3. Merchant of Record, Subscriptions &amp; Global Tax</h2>
            <p>
              Access to premium rulesets, enterprise exports, and automated CI/CD gates requires an active subscription (Pro or Enterprise). <strong>Polar Software Inc. serves as the official Merchant of Record (MoR) for all Zelsis software subscriptions, orders, and financial transactions.</strong>
            </p>
            <p>
              As the Merchant of Record, Polar is responsible for digital order processing, customer billing inquiries, automated EU VAT / international sales tax calculation and remittance, and compliance with PCI-DSS Level 1 payment security standards. Subscriptions renew automatically until cancelled via the customer billing portal.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">4. Acceptable Use &amp; Code Ownership</h2>
            <p>
              You represent that you own or possess valid licensing rights for all repositories submitted to the scanner. You agree not to: (a) scan repositories without proper authorization; (b) reverse-engineer or attempt to extract proprietary source algorithms of the Zelsis scanner engine; or (c) probe, scan, or breach system boundaries or rate limit controls.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">5. Limitation of Liability &amp; Warranty Disclaimer</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ZELSIS IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. IN NO EVENT SHALL ZELSIS, ITS OFFICERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA CORRUPTION, DEPLOYMENT DOWNTIME, OR REGULATORY FINES ARISING FROM THE USE OF THE SERVICE.
            </p>
            <p>
              OUR TOTAL AGGREGATE LIABILITY UNDER THESE TERMS SHALL NOT EXCEED THE TOTAL AMOUNT ACTUALLY PAID BY YOU TO ZELSIS IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">6. Termination &amp; Account Erasure</h2>
            <p>
              You may cancel your subscription or terminate your account at any time via the Project Settings dashboard. We reserve the right to suspend or terminate accounts that violate acceptable use or attempt malicious exploitation of platform infrastructure.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">7. Governing Law &amp; Jurisdiction</h2>
            <p>
              These Terms and any dispute arising out of or related to them shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without giving effect to any choice or conflict of law provision. Any legal suit, action, or proceeding arising out of or related to these Terms shall be instituted exclusively in the federal or state courts located in Delaware.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-base font-bold text-[#FFFFFF]">8. Contact &amp; Notices</h2>
            <p className="font-mono text-xs text-emerald-400">
              Legal Inquiries: legal@zelsis.com // Support: contact@zelsis.com
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
