import os
import re

file_path = r"c:\Users\Bedirhan\Desktop\newday\lib\scanner-engine.ts"
with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

translations = [
    ("Mor-Mavi Gradyan İstilası", "Generic Purple-Blue Gradient Cliché"),
    ("Mor-mavi gradyan algılandı", "Purple-blue gradient overuse detected"),
    ("Jenerik Mor-Mavi Neon Gradyan Kullanımı", "UI-01: Generic Purple-Blue Neon Gradient Cliché"),
    ("Sihirli Değnek (✨) / Sparkle İkon İstilası", "UI-03: Overused Sparkle (✨) / Magic Wand Icon Cliché"),
    ("Sparkle ikon kullanımı algılandı", "Sparkle icon overuse detected"),
    ("Boş Durum (Empty State) Yokluğu", "UI-04: Absence of Empty State Fallback Component"),
    ("Eksik Empty State algılandı", "Missing Empty State component detected"),
    ("Chat Wrapper Tuzağı", "Chat-Wrapper UI Trap"),
    ("Sadece Chat Arayüzüne Mahkum Etmek (Chat-Wrapper Trap)", "UI-07: Conversational Chat-Wrapper Lock-In Trap"),
    ("Chat-wrapper tuzağı detected", "Chat-wrapper lock-in detected"),
    ("Belirsiz Spinner \"AI Düşünüyor...\"", "Uninformative \"AI Thinking...\" Spinner"),
    ("Gereksiz \"AI Düşünüyor...\" Spinner'ı", "UI-11: Uninformative \"AI Thinking...\" Spinner Cliché"),
    ("Veritabanı taranıyor...", "Scanning database tables..."),
    ("Sonuçlar derleniyor...", "Synthesizing audit findings..."),
    ("Klişe Dolgu Cümleleri (Fluff)", "Cliché Fluff & Filler Prefaces"),
    ("Klişe Dolgu Cümleleri (Fluff) Algılandı", "UI-21: Generic Cliché Fluff & Filler Prefaces"),
    ("Klişe dolgu girizgahı detected", "Cliché filler text detected"),
    ("Robotik Özürler (As an AI language model...)", "Robotic AI Apologies (As an AI language model...)"),
    ("Robotik Özür / Ret Cümlesi (As an AI language model...)", "UI-23: Robotic Apology / Refusal Boilerplate"),
    ("Robotik özür metni detected", "Robotic AI apology boilerplate detected"),
    ("Aşırı Meta-Duyurular", "Excessive Meta-Announcement Statements"),
    ("Aşırı Meta-Duyuru Girizgahı", "UI-32: Excessive Meta-Announcement Preface Cliché"),
    ("Meta-duyuru cümlesi detected", "Meta-announcement text detected"),
    ("Biçimsel Tutarsızlık (Missing Schema / Structured Outputs)", "Missing Structured Schema Validation"),
    ("Eksik Structured Outputs (Zod / JSON Schema Eksikliği)", "UI-39: Unvalidated Dynamic Outputs (Missing Zod Schema)"),
    ("Eksik Structured Output şeması detected", "Missing Structured Zod schema detected"),
    ("Prompt Şişkinliği (Monolithic System Prompt Bloat)", "Monolithic System Prompt Inflation"),
    ("Prompt Şişkinliği (Monolithic System Prompt Bloat)", "UI-41: Monolithic System Prompt Inflation"),
    ("Prompt şişkinliği detected", "System prompt inflation detected"),
    ("Dinamik Değişken Enjeksiyon Hataları", "Dynamic Variable Injection Failures"),
    ("Dinamik Değişken Enjeksiyonu ve Fallback Eksikliği", "UI-48: Dynamic Variable Injection Missing Fallback"),
    ("Fallback'siz değişken enjeksiyonu detected", "Variable injection missing fallback detected"),
    ("Deterministik Görevlerde Yüksek Sıcaklık", "High Temperature on Deterministic Tasks"),
    ("Deterministik / JSON Görevinde Yüksek Sıcaklık (High Temperature)", "UI-57: Excessive Temperature Setting on Deterministic Task"),
    ("Yüksek temperature parametresi detected", "Excessive temperature parameter detected"),
    ("Kötü Chunking (Naive Fixed Character Text Splitter)", "Naive Fixed-Character Chunking"),
    ("Naive Fixed-Length Text Chunking (Kötü Parçalama)", "UI-61: Naive Fixed-Character Text Splitter"),
    ("Yetkisiz Veri Sızıntısı (Multi-Tenant RAG Leakage)", "Multi-Tenant RAG Data Leakage"),
    ("Vektör Arama Yetkisiz Veri Sızıntısı (Missing Multi-Tenant Metadata Filter)", "UI-75: Unfiltered Multi-Tenant Vector Query"),
    ("Multi-tenant vector query sızıntısı detected", "Unfiltered multi-tenant vector query detected"),
    ("Veri Yokken Halüsinasyona Kaçış", "Context Hallucination Vulnerability"),
    ("RAG Eksik Bağlam Halüsinasyon Guardrail Yokluğu", "UI-76: Missing RAG Hallucination Guardrail"),
    ("Bilgi bulunamadı", "Information not found"),
    ("Geri Dönüşü Olmayan İşlemlerin Onaysız Yapılması (Human-in-the-Loop)", "Destructive Action Missing Human Approval"),
    ("Yıkıcı Ajan Eyleminde İnsan Onayı (Human-in-the-Loop) Eksikliği", "UI-85: Destructive Agent Action Missing Human-in-the-Loop Approval"),
    ("Human-in-the-Loop onay adımı missingliği detected", "Human-in-the-loop approval step missing"),
    ("Hassas Verilerin Tool Loglarına Düşmesi", "Sensitive Data Exposure in Tool Logs"),
    ("Hassas Verilerin Tool Loglarına Sızması (Unredacted Tool Log)", "UI-90: Unredacted Sensitive Data in Tool Logs"),
    ("Maskelenmemiş tool logu detected", "Unredacted sensitive tool log detected"),
    ("Kullanıcı İptal Eylemini Desteklememek (AbortController / Signal)", "Missing User Request Abort Signal"),
    ("Kullanıcı İptal Sinyali Desteklenmemesi (Missing AbortController)", "UI-100: Missing Request AbortSignal Listener"),
    ("AbortController sinyali missingliği detected", "Missing AbortController signal listener detected"),
    ("Boş catch bloğu detected", "Empty catch block detected"),
    ("Tip Güvenliği İllüzyonu (TypeScript Any Escape)", "TypeScript Any Type Safety Escape"),
    ("TypeScript \"any\" Tip Kaçışı (Overused Any Types)", "UI-111: TypeScript \"any\" Type Escape"),
    ("Overused Any types detected", "Overused 'any' types detected"),
    ("Sert Renk Kontrastı & Neon Parlama Hatası", "High-Contrast Neon Glow Accent"),
    ("Aşırı Kontrastlı Neon Renk / Parlama Görsel Hatası", "UI-115: High-Contrast Neon Glow Accent Violation"),
    ("Görsel aşırı neon parlama detected", "Excessive neon glow accent detected"),
    ("Eksik Form Label Bağlantısı (htmlFor / id)", "Unassociated Form Field Label"),
    ("Form Label Bağlantı Eksikliği (Missing htmlFor / id)", "UI-120: Unassociated Form Field Label (Missing htmlFor / id)"),
    ("Form label htmlFor eksikliği detected", "Form label missing htmlFor association detected"),
    ("Düğme / Input Yüklenme Durumu Yokluğu", "Missing Loading & Disabled Button State"),
    ("Eksik Action Yüklenme & Pasif Durumu (Disabled State)", "UI-125: Missing Button Loading & Disabled Pending State"),
    ("Eksik disabled loading durumu detected", "Missing button loading state detected"),
    ("Sabit Yükseklik / Metin Taşması Hatası", "Fixed Height Container Text Truncation"),
    ("Kapsayıcı Metin Sıkışması ve Taşma Riskleri", "UI-130: Fixed Height Container Text Truncation Risk"),
    ("Sabit yükseklik metin taşma riski detected", "Fixed height container text truncation risk detected"),
    ("Dinamik Liste Rendering'de Key Prop Eksikliği", "Missing Key Prop in Dynamic Array Rendering"),
    ("Dinamik Render'da Key Prop Eksikliği", "UI-140: Missing Key Prop in Array Map Rendering"),
    ("Eksik key prop detected", "Missing key prop detected in map callback"),
    ("Karanlık Temada Sert Siyah Arka Plan", "Raw Pitch Black Z-Index Surface"),
    ("Aşırı Siyah (Pure #000) Zemin ve Z-Index Karışıklığı", "UI-150: Pitch Black Surface & Low Contrast Tokens"),
    ("Sert siyah zemin kullanımı detected", "Raw pitch black background token detected"),
    ("Aşırı Animasyon ve Layout Shift Hatası", "Excessive Unbounded Micro-Animations"),
    ("Kontrolsüz Animasyon Süresi ve Layout Shift Riski", "UI-160: Unbounded Micro-Animations & Layout Shift Risk"),
    ("Kontrolsüz animasyon süresi detected", "Unbounded animation duration detected"),
    ("Tıklanabilir Öğelerde Hover / Focus Durum Yokluğu", "Missing Interactive Hover & Keyboard Focus Ring"),
    ("İnteraktif Elemanlarda Hover ve Keyboard Focus Eksikliği", "UI-170: Missing Hover Effect & Keyboard Focus Ring"),
    ("Eksik focus/hover kuralı detected", "Missing focus/hover ring style detected"),
    ("İnteraktif Elemanlarda A11y Aria-Label Yokluğu", "Missing Accessibility ARIA Attributes"),
    ("Erişilebilirlik Aria-Label ve Role Eksikliği", "UI-180: Missing ARIA Label & Role Attributes"),
    ("Eksik aria-label/role detected", "Missing aria-label attribute detected"),
    ("Mobil Dokunma Hedefi (Touch Target) Yetersizliği", "Inadequate Mobile Touch Target Area"),
    ("Dar Dokunma Hedefi (Touch Target Size < 44px)", "UI-190: Inadequate Mobile Touch Target Size (<44px)"),
    ("Dar touch target boyutu detected", "Small touch target size detected"),
    ("Sabit Versiyon Etiketi Yokluğu", "Unpinned API / Package Version Dependencies"),
    ("Sabit Versiyon Bağımlılığı Yokluğu (Unpinned Version)", "UI-197: Unpinned Dependency / Provider Model Version"),
    ("Sabit versiyon bağımlılığı missingliği detected", "Unpinned dependency version detected")
]

for old_s, new_s in translations:
    content = content.replace(old_s, new_s)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Successfully translated ALL scanner-engine.ts titles, logs, and comments into 100% pure English!")
